export const colors = {
  background: '#F7FBFB',
  surface: '#FFFFFF',
  surfaceMuted: '#F4F7F8',
  surfaceElevated: '#F9FCFC',
  text: '#0B0B0B',
  textMuted: '#7A7A7A',
  border: '#D9E1E3',
  black: '#000000',
  white: '#FFFFFF',
  primary: '#2EC4C7',
  primaryPressed: '#22B5B9',
  primarySoft: '#EAF9F9',
  gold: '#2EC4C7',
  goldDeep: '#22B5B9',
  goldSoft: '#EAF9F9',
  grayLight: '#F4F7F8',
  grayMedium: '#D9E1E3',
  grayDark: '#7A7A7A',
  success: '#2E8B57',
  successSoft: '#E8F5EE',
  error: '#C24B4B',
  errorSoft: '#FBECEC',
};

export default colors;
